#!/sbin/openrc-run
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

depend() {
	before xorg
}

start() {
	ebegin "Starting pulseaudio"
	PA_ALL_OPTS="${PA_OPTS} --fail=1 --daemonize=1 --system --high-priority"
	start-stop-daemon --start --exec /usr/bin/pulseaudio -- ${PA_ALL_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping pulseaudio"
	start-stop-daemon --stop --quiet --exec /usr/bin/pulseaudio --pidfile /var/run/pulse/pid
	eend $?
}
